export const ADD_WORD = 'ADD_WORD'
export const LOAD_WORD = 'LOAD_WORD'
export const LIKE_WORD = 'LIKE_WORD'
export const SHOW_ERR = 'SHOW_ERR'
export const SORT_WORD = 'SORT_WORD'
export const PARTS_OF_SPEECH = 'PARTS_OF_SPEECH'
